services:

  users_postgres:
    image: postgres:latest
    container_name: users_postgres
    env_file:
      - .env
    networks:
      - database-network
    ports:
      - "6666:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d users" ]
      interval: 1s
      timeout: 1s
      retries: 10

  users_server:
    build: .
    container_name: users_server
    depends_on:
      users_postgres:
        condition: service_healthy
    env_file:
      - .env
    command: python server/main.py
    ports:
      - 8888:8888
    networks:
      - shared-network
      - database-network

networks:
  database-network:
    driver: bridge
    external: true

  shared-network:
    driver: bridge
    external: true
