services:

  users_postgres:
    image: postgres:latest
    container_name: users_postgres
    env_file:
      - .env
    networks:
      - users-internal-network
    ports:
      - "6666:5432"

  users_server:
    build: .
    container_name: users_server
    depends_on:
      - users_postgres
    env_file:
      - .env
    command: python server/main.py
    ports:
      - 8888:8888
    networks:
      - shared-network
      - users-internal-network

networks:
  users-internal-network:
    driver: bridge
    internal: true

  shared-network:
    driver: bridge
    external: true
