components:
  schemas:
    ApiErrorResponse:
      properties:
        exceptionMessage:        
          title: Exceptionmessage
          type: string
      required:
      - exceptionMessage
      title: ApiErrorResponse
      type: object
    AuthUserRequest:
      properties:
        login:
          title: Login
          type: string
        password:
          title: Password
          type: string
      required:
      - login
      - password
      title: AuthUserRequest
      type: object
    ChangeInfoRequest:
      properties:
        birthday:
          anyOf:
          - format: date
            type: string
          - type: 'null'
          title: Birthday
        city:
          anyOf:
          - type: string
          - type: 'null'
          title: City
        email:
          anyOf:
          - type: string
          - type: 'null'
          title: Email
        name:
          anyOf:
          - type: string
          - type: 'null'
          title: Name
        phone_number:
          anyOf:
          - type: string
          - type: 'null'
          title: Phone Number
        surname:
          anyOf:
          - type: string
          - type: 'null'
          title: Surname
        token:
          title: Token
          type: string
      required:
      - token
      - name
      - surname
      - birthday
      - email
      - phone_number
      - city
      title: ChangeInfoRequest
      type: object
    RegisterUserRequest:
      properties:
        email:
          title: Email
          type: string
        login:
          title: Login
          type: string
        password:
          title: Password
          type: string
      required:
      - login
      - password
      - email
      title: RegisterUserRequest
      type: object
    SuccesfulAuthResponse:
      properties:
        token:
          title: Token
          type: string
      required:
      - token
      title: SuccesfulAuthResponse
      type: object
info:
  title: users
  version: 0.1.0
openapi: 3.1.0
paths:
  /auth:
    post:
      operationId: auth_user_auth_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthUserRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/SuccesfulAuthResponse'
                - $ref: '#/components/schemas/ApiErrorResponse'
                title: Response Auth User Auth Post
          description: Успешная авторизация
        '400':
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/ApiErrorResponse'
                - type: 'null'
                title: Response Change Info Change Info Post
          description: Пользователь с такими данными не найден
      summary: Auth User
      tags:
      - auth
  /change_info:
    post:
      operationId: change_info_change_info_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangeInfoRequest'
        required: true
      responses:
        '200':
          description: Данные успешно изменены
        '400':
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/ApiErrorResponse'
                - type: 'null'
                title: Response Change Info Change Info Post
          description: Пользователь с таким токеном не найден
      summary: Change Info
      tags:
      - change_info
  /register:
    post:
      operationId: register_user_register_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUserRequest'
        required: true
      responses:
        '200':
          description: Успешная регистрация
        '400':
          content:
            application/json:
              schema:
                anyOf:
                - $ref: '#/components/schemas/ApiErrorResponse'
                - type: 'null'
                title: Response Change Info Change Info Post
          description: Логин уже существует
      summary: Register User
      tags:
      - register