services:

  posts_postgres:
    image: postgres:latest
    container_name: posts_postgres
    env_file:
      - .env
    networks:
      - database-network
    ports:
      - "6667:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d posts" ]
      interval: 1s
      timeout: 1s
      retries: 10

  posts_server:
    build: .
    container_name: posts_server
    depends_on:
      posts_postgres:
        condition: service_healthy
    env_file:
      - .env
    command: python server/main.py
    ports:
      - 9999:9999
    networks:
      - shared-network
      - database-network

networks:
  database-network:
    driver: bridge
    external: true

  shared-network:
    driver: bridge
    external: true
