services:

  posts_postgres:
    image: postgres:latest
    container_name: posts_postgres
    env_file:
      - .env
    ports:
      - "6667:5432"

  posts_server:
    build: .
    container_name: posts_server
    depends_on:
      - posts_postgres
    env_file:
      - .env
    command: python server/main.py
    ports:
      - 9999:9999
    networks:
      - shared-network

networks:
  shared-network:
    external: true
