---
title: users
---
erDiagram
    accounts {
        SERIAL PRIMARY KEY id
        VARCHAR(63) name
        VARCHAR(63) surname
        TIMESTAMP creation_timestamp
        VARCHAR(31) role
    }
    logins {
        INTEGER REFERENCES accounts(id) account_id
        VARCHAR(63) login
        VARCHAR(63) hashed_password
        BOOLEAN is_freezed
        INTEGER login_tries_in_1h
    }
    user_info {
        INTEGER account_id
        VARCHAR(63) city
        VARCHAR(63) email
        VARCHAR(15) phone_number
        TIMESTAMP last_login
    }

    accounts ||--|| logins : ""
    accounts ||--|| user_info : ""
